import re

class ActionExecutor:
    """
    Executes tool actions generated by the LLM.
    """

    def __init__(self, tool_registry):
        self.tool_registry = tool_registry

    def execute(self, action_text):

        """
        Expected format from LLM:

        ACTION: web_search
        INPUT: AI impact on software development
        """

        action_match = re.search(r"ACTION:\s*(\w+)", action_text)
        input_match = re.search(r"INPUT:\s*(.*)", action_text)

        if not action_match:
            return {"status": "error", "message": "No ACTION found"}

        tool_name = action_match.group(1)
        tool_input = input_match.group(1) if input_match else ""

        tool = self.tool_registry.get_tool(tool_name)

        if not tool:
            return {"status": "error", "message": f"Tool {tool_name} not found"}

        result = tool.run(tool_input)

        return {
            "status": "success",
            "tool": tool_name,
            "result": result
        }